### ISSUE TITLE
[Help request] Can't get dumber gist work on Brave in an iframe.

### ISSUE THREAD

**Issue by bigopon** [dumberjs/dumber-gist#19]
Simply navigate to https://buttonwoodcx.github.io/doc-bcx-validation/examples/foreach-and-nested on Brave browser, can't seem to get it to work even when turning off the shield

Getting FS errors, something like this:
![image](https://user-images.githubusercontent.com/9994529/75541889-c8366100-5a72-11ea-8b67-eb7bb7c28049.png)

**Comment by 3cp** [comment]
I saw different error. Somehow brave prevented the nested iframe (the embedded app iframe in the dumber-gist example iframe).

```
__boot-up-worker.html:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://5887cc0e17694eb2261c5e6d2776b600.gist.dumber.app/') with script ('https://5887cc0e17694eb2261c5e6d2776b600.gist.dumber.app/__dumber-gist-worker.js'): The user denied permission to use Service Worker.
```

**Comment by bigopon** [comment]
So, i checked and saw this
![image](https://user-images.githubusercontent.com/9994529/75598387-6831d000-5aef-11ea-9aaf-608d4885ca80.png)

The cookies at [hash].gist.dumber.app is blocked, even with my allowance for:
![image](https://user-images.githubusercontent.com/9994529/75598404-85ff3500-5aef-11ea-8223-781ef9d65c1a.png)

It seems `[hash].gist.dumber.app` is considered a different site

**Comment by bigopon** [comment]
and it seems to work fine on FF for me now, after I added the same config above

**Comment by bigopon** [comment]
It also works fine on Chrome after the permission above

**Comment by 3cp** [comment]
I am confused why Chrome and Brave (save engine) requires cross-origin cookie for service worker to work.

There is no doc said service worker needs cookie at all. I could not find any clear explanation.

In comparison, even I turn on "block all cookies" in Safari, dumber-gist still works in iframe. Safari clearly didn't check cookie permission for service worker.

**Comment by 3cp** [comment]
Dumber-gist itself uses no cookie at all.

**Comment by 3cp** [comment]
One thing might be related, cloudflare created a cookie `__cfduid` on domain `.dumber.ap`.

**Comment by 3cp** [comment]
https://github.com/brave/brave-browser/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+iframe

**Comment by bigopon** [comment]
Thats a lot of issues. Though codesandbox works for me in iframe

**Comment by 3cp** [comment]
Probably my limited understanding on service worker.

codesandbox can fall back to use backend, that might help.

**Comment by 3cp** [comment]
Will try sandbox attribute tomorrow https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/

I guess both brave and safari had implicitly turned on some sandbox on iframe without sandbox attribute. They manifested into different issues.

allow-same-origin is probably the critical restriction to be lift off.

**Comment by 3cp** [comment]
Nope :-(
It didn't help Brave with `sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"`.
Although the additional sandbox attribute still worked in other browsers.

**Comment by 3cp** [comment]
It did fix brave by turning off one config in brave shields.

Cookies, from "Only block cross-site cookies" to "All all cookies".

BTW, it's hyper confusing that Chromium (and Brave) uses term "cookies" to mean "cookies, and localStorage and few other things".

**Comment by 3cp** [comment]
![Screen Shot 2020-03-04 at 9 36 40 am](https://user-images.githubusercontent.com/1188806/75826471-ac78e500-5dfb-11ea-876e-aaebcdca2145.png)

Turning shields off also worked for me.

**Comment by 3cp** [comment]
I need to detect brave browser (and shields if possible), then tell user what to do if service worker didn't boot up after timeout.

**Comment by 3cp** [comment]
https://github.com/brave/brave-browser/issues/8216

**Comment by 3cp** [comment]
Partially addressed this issue by telling user what to do when service worker failed.

**Comment by 3cp** [comment]
@bigopon is this considered "fixed"? Dumber gist now shows some readable error message on failed service-worker, notifies user how to get around browser issue.

**Comment by bigopon** [comment]
Yes, thanks @3cp . The solution is to upgrade to latest Brave
