### ISSUE TITLE
[Feature Request] Ctrl Enter should submit form when saving gist

### ISSUE THREAD

**Issue by bigopon** [dumberjs/dumber-gist#20]
![image](https://user-images.githubusercontent.com/9994529/75605923-b10f7600-5b3b-11ea-96c0-d825c60bc83a.png)

**Comment by 3cp** [comment]
If switch textarea to input, form can handle "enter" for submit.

Description in github gist is actually single line string, but has no problem to save a string with line breaks.

Probably I should not use textarea for it.
