### ISSUE TITLE
TODO support list gists pages

### ISSUE THREAD

**Issue by 3cp** [dumberjs/dumber-gist#28]
My own gists grew to more than 1 page now.

https://developer.github.com/v3/gists/#list-gists-for-a-user

The `Link` header from response tells about pages information.

```
Status: 200 OK
Link: <https://api.github.com/resource?page=2>; rel="next",
      <https://api.github.com/resource?page=5>; rel="last"
```

**Comment by 3cp** [comment]
https://developer.github.com/v3/#pagination
https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by 3cp** [comment]
@Sayan751 done.

**Comment by Sayan751** [comment]
@3cp Awesome. Thank you :)
